In [29]:
import tensorflow
from tensorflow.keras.preprocessing import image 
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input

import numpy as np 
from numpy.linalg import norm


In [3]:
# doing it for one image
# bringing the image in the same format as the model

img = image.load_img('images/1163.jpg', target_size=(224, 224))

In [4]:
# converting the image to array

imgArray = image.img_to_array(img)


In [6]:
print(imgArray)

[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]


In [8]:
imgArray.shape

(224, 224, 3)

In [10]:
# converting imgArray dimensions 224,224,3 to 1,224,224,3
# why ? because keras work on batches of images not single image

# if you have 100 images then you will have 100,224,224,3
# if you have single image you have to tell keras that it is a batch of 1 image
# resizing images 
# will give 4D array

expandedImgArray = np.expand_dims(imgArray, axis=0)

 

In [11]:
expandedImgArray

array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        ...,

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
       

In [12]:
expandedImgArray.shape

(1, 224, 224, 3)

In [14]:
# Creating the ResnEt50 model and loading the weights, top layer is false because we will add own ours
# Standard Image size 224, 224, 3

model = ResNet50(weights='imagenet', include_top=False,
                 input_shape=(224, 224, 3))


In [17]:
model.trainable = False
model = tensorflow.keras.Sequential([model, GlobalMaxPooling2D()])


In [18]:
# preprocessing the image
# preprocess_input is a function that will format the image into the format that the model expects

preprocessedImg = preprocess_input(expandedImgArray)

In [19]:
print(preprocessedImg.shape)
preprocessedImg

(1, 224, 224, 3)


array([[[[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        ...,

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,


In [20]:
model.predict(preprocessedImg)

array([[ 1.6351392, 19.32439  ,  1.808047 , ...,  1.1685898, 17.437454 ,
        12.0990305]], dtype=float32)

In [23]:
model.predict(preprocessedImg).shape

# 1 image and 2048 features/embedding values

(1, 2048)

In [24]:
# flatten the array to convert into 1D array

model.predict(preprocessedImg).flatten().shape


(2048,)

In [30]:
# we are dividing by the norm of the vector to normalize the vector means to make the vector length 1 dividing every number with 313.5
model.predict(preprocessedImg).flatten()/norm(model.predict(preprocessedImg).flatten())

array([0.00491867, 0.05812978, 0.00543879, ..., 0.00351524, 0.05245368,
       0.03639515], dtype=float32)